[package]
name = "deucalion-rs"
version = "0.1.0"
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]

[dependencies]
hlua = "0.3"
sfml = "0.12"
log = "0.3"
env_logger = "0.4.3"
tiled = "0.6.0"
update_rate = "1"
